### ISSUE TITLE
Iframe preview does not appear to be working:

### ISSUE THREAD

**Issue by ViolanteCodes** [ButterCMS/rails-starter-buttercms#3]
@jirkamotejl 

Great job on this app - 99 percent of everything is working as expected. Was a breeze to test so far!

It doesn't look like iframe preview from the butter preview panel is working for me:
https://share.getcloudapp.com/5zurOEmK

**Comment by jirkamotejl** [comment]
@ViolanteCodes 

Thank you for this catch! It's my bad, I overlooked that one. However, I managed to fix it and then went ahead and merged a [PR](https://github.com/ButterCMS/rails-starter-buttercms/pull/4) into the main branch, so you can see for yourself.

**Comment by ViolanteCodes** [comment]
@jirkamotejl LGTM!
